# -*- coding: utf-8 -*-
"""ProyectoIA-ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNcFSd-AzpnUmnVkwFDjJjsaO0dCkcuE
"""

#!pip install -U langchain

#!pip install langchain-google-genai

#!pip install python-dotenv

import math
import os

# Install Gradio
#!pip install -qU gradio
import gradio as gr
from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain.agents.middleware import SummarizationMiddleware
from langchain.tools import tool

#!pip install -qU ddgs langchain-community
from langchain_community.tools import DuckDuckGoSearchRun
from langchain_core.messages import AIMessage, HumanMessage
from langchain_core.runnables import RunnableConfig
from langgraph.checkpoint.memory import InMemorySaver

load_dotenv()

os.environ["GOOGLE_API_KEY"] = os.getenv("GEMINI_API_KEY")

print(os.environ["GOOGLE_API_KEY"])


# Initialize the DuckDuckGoSearchRun instance
ddg_search_runner = DuckDuckGoSearchRun()


# Create a LangChain Tool from the DuckDuckGoSearchRun instance
@tool(
    "search_web",
    description="Use this tool to search the internet for general knowledge or current events.",
)
def search(query: str) -> str:
    """Search the web for the given query."""
    return ddg_search_runner.run(query)


@tool(
    "calculator",
    description="Performs arithmetic calculations. Use this for any math problems.",
)
def calc(expression: str) -> str:
    """Evaluate mathematical expressions."""
    # Define a safe global dictionary for eval, making math.sqrt available as sqrt()
    safe_globals = {
        "__builtins__": {},  # Restrict built-ins for security
        "math": math,  # Keep math module available if user uses math. prefix
        "sqrt": math.sqrt,  # Make sqrt directly accessible without 'math.' prefix
    }

    try:
        result = eval(expression, safe_globals)
        return str(result)
    except Exception as e:
        return f"Error: {e}. Please ensure the expression is valid."


@tool("get_weather", description="Get the current weather for a given location.")
def get_weather(city: str) -> str:
    """Get weather for a given city."""
    return f"It's always sunny in {city}!"


checkpointer = InMemorySaver()

agent = create_agent(
    model="google_genai:gemini-2.5-flash-lite",
    tools=[get_weather, search, calc],
    checkpointer=checkpointer,
    middleware=[
        SummarizationMiddleware(
            model="google_genai:gemini-2.5-flash-lite",
            trigger=("tokens", 2000),
            keep=("messages", 20),
        )
    ],
    system_prompt="You are a helpful assistant",
)

config: RunnableConfig = {"configurable": {"thread_id": "1"}}


"""### Interfaz de Chat con Gradio

Ahora, crearemos una función que el Gradio ChatInterface usará para interactuar con el agente. Esta función tomará el mensaje del usuario y el historial de chat, invocará al agente y devolverá la respuesta del agente junto con el historial actualizado.
"""


def chat_with_agent(message, history):
    global config  # Ensure config (thread_id) is accessible

    langchain_messages = []
    # Gradio history is a list of lists: [[user_msg, bot_msg], ...]
    # Convert Gradio history to LangChain message format for the agent
    for i, item in enumerate(history):
        if not (isinstance(item, (list, tuple)) and len(item) == 2):
            print(
                f"Warning: History item at index {i} is not a valid [human, ai] pair and will be skipped: {item}"
            )
            continue

        human, ai = item
        if human:
            langchain_messages.append(HumanMessage(content=human))
        if ai:
            langchain_messages.append(AIMessage(content=ai))

    # Add the current user message
    langchain_messages.append(HumanMessage(content=message))

    try:
        # Invoke the agent
        response = agent.invoke({"messages": langchain_messages}, config)

        # Extract the agent's latest response
        agent_response = response["messages"][-1].content
    except Exception as e:
        agent_response = (
            f"Lo siento, ha ocurrido un error al procesar tu solicitud: {e}"
        )

    # For this example, we'll just return the final AI message content.
    # The Gradio `ChatInterface` automatically handles appending the user's message
    # and then expects our function to return the agent's response for that last message.

    return agent_response


"""### Lanzar la Interfaz de Chat

Finalmente, creamos y lanzamos la interfaz de Gradio.
"""

iface = gr.ChatInterface(
    fn=chat_with_agent,
    chatbot=gr.Chatbot(height=400),
    textbox=gr.Textbox(
        placeholder="Escribe tu mensaje aquí...", container=False, scale=7
    ),
    title="Agente Conversacional con LangChain y Gradio",
    description="Interactúa con el agente LangChain usando esta interfaz de chat impulsada por Gradio. Puedes preguntar sobre tu nombre, poemas, e investigar temas en la web.",
    examples=[
        "Hi, my name is Alice",
        "Write a short poem about the ocean",
        "How is the weather in Guatemala City",
        "What is the square root of 2?",
    ],
    cache_examples=True,
)

iface.launch(debug=True, share=True)
